default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>
  timeout: 100
  default_transaction_mode: immediate

development:
  primary:
    <<: *default
    database: storage/tenants/%{tenant}/db/development.sqlite3
    tenanted: true

test:
  primary:
    <<: *default
    database: storage/tenants/%{tenant}/db/test.sqlite3
    tenanted: true

production:
  primary:
    <<: *default
    database: storage/tenants/%{tenant}/db/production.sqlite3
    tenanted: true
